//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SafeMeasureTicketTemp", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Service")]
    public partial class SafeMeasureTicketTemp : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BeLongAreaCodeField;
        
        private string BeLongAreaIdField;
        
        private string BeLongAreaNameField;
        
        private System.DateTime EndDateField;
        
        private string HazardLevelField;
        
        private string IdField;
        
        private System.DateTime StartDateField;
        
        private string TicketNumberField;
        
        private string WorkContentField;
        
        private string WorkPrincipalField;
        
        private string WorkUnitField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeLongAreaCode
        {
            get
            {
                return this.BeLongAreaCodeField;
            }
            set
            {
                this.BeLongAreaCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeLongAreaId
        {
            get
            {
                return this.BeLongAreaIdField;
            }
            set
            {
                this.BeLongAreaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeLongAreaName
        {
            get
            {
                return this.BeLongAreaNameField;
            }
            set
            {
                this.BeLongAreaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HazardLevel
        {
            get
            {
                return this.HazardLevelField;
            }
            set
            {
                this.HazardLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketNumber
        {
            get
            {
                return this.TicketNumberField;
            }
            set
            {
                this.TicketNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkContent
        {
            get
            {
                return this.WorkContentField;
            }
            set
            {
                this.WorkContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkPrincipal
        {
            get
            {
                return this.WorkPrincipalField;
            }
            set
            {
                this.WorkPrincipalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkUnit
        {
            get
            {
                return this.WorkUnitField;
            }
            set
            {
                this.WorkUnitField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFuelService")]
public interface IFuelService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdateFuelChecking", ReplyAction="http://tempuri.org/IFuelService/UpdateFuelCheckingResponse")]
    void UpdateFuelChecking(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpateReport", ReplyAction="http://tempuri.org/IFuelService/UpateReportResponse")]
    int UpateReport(string id, string upload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpateRmrb", ReplyAction="http://tempuri.org/IFuelService/UpateRmrbResponse")]
    int UpateRmrb(string id, string upload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SaveBMCompanyMaintain", ReplyAction="http://tempuri.org/IFuelService/SaveBMCompanyMaintainResponse")]
    int SaveBMCompanyMaintain(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SaveBMIndexMaintain", ReplyAction="http://tempuri.org/IFuelService/SaveBMIndexMaintainResponse")]
    int SaveBMIndexMaintain(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdateProblemRectifyBM", ReplyAction="http://tempuri.org/IFuelService/UpdateProblemRectifyBMResponse")]
    int UpdateProblemRectifyBM(string strId, string finishstatus, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/GetSafeMeasureTicketData", ReplyAction="http://tempuri.org/IFuelService/GetSafeMeasureTicketDataResponse")]
    WcfService.Service.SafeMeasureTicketTemp[] GetSafeMeasureTicketData();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdateFuelSupplierApply", ReplyAction="http://tempuri.org/IFuelService/UpdateFuelSupplierApplyResponse")]
    void UpdateFuelSupplierApply(string strId, string strType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SaveFuelSupplier", ReplyAction="http://tempuri.org/IFuelService/SaveFuelSupplierResponse")]
    void SaveFuelSupplier(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SaveFactoryInfo", ReplyAction="http://tempuri.org/IFuelService/SaveFactoryInfoResponse")]
    int SaveFactoryInfo(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SavePurchaseType", ReplyAction="http://tempuri.org/IFuelService/SavePurchaseTypeResponse")]
    int SavePurchaseType(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SaveFuelKind", ReplyAction="http://tempuri.org/IFuelService/SaveFuelKindResponse")]
    int SaveFuelKind(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SaveTransportType", ReplyAction="http://tempuri.org/IFuelService/SaveTransportTypeResponse")]
    int SaveTransportType(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SavePlanFactoryFee", ReplyAction="http://tempuri.org/IFuelService/SavePlanFactoryFeeResponse")]
    int SavePlanFactoryFee(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SaveMine", ReplyAction="http://tempuri.org/IFuelService/SaveMineResponse")]
    int SaveMine(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SaveStationInfo", ReplyAction="http://tempuri.org/IFuelService/SaveStationInfoResponse")]
    int SaveStationInfo(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/SavePlanFundVindicate", ReplyAction="http://tempuri.org/IFuelService/SavePlanFundVindicateResponse")]
    int SavePlanFundVindicate(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdateFuelContract", ReplyAction="http://tempuri.org/IFuelService/UpdateFuelContractResponse")]
    int UpdateFuelContract(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanZBMonth", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanZBMonthResponse")]
    void UpdatePlanZBMonth(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanZBYear", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanZBYearResponse")]
    void UpdatePlanZBYear(byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanElecYear", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanElecYearResponse")]
    void UpdatePlanElecYear(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanElecMonth", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanElecMonthResponse")]
    void UpdatePlanElecMonth(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanHotYear", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanHotYearResponse")]
    void UpdatePlanHotYear(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanHotMonth", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanHotMonthResponse")]
    void UpdatePlanHotMonth(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanJJYear", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanJJYearResponse")]
    void UpdatePlanJJYear(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanJJMonth", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanJJMonthResponse")]
    void UpdatePlanJJMonth(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanFuelYear", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanFuelYearResponse")]
    void UpdatePlanFuelYear(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanFuelMonth", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanFuelMonthResponse")]
    void UpdatePlanFuelMonth(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdateNewSetStockYear", ReplyAction="http://tempuri.org/IFuelService/UpdateNewSetStockYearResponse")]
    void UpdateNewSetStockYear(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdateColligateSPYear", ReplyAction="http://tempuri.org/IFuelService/UpdateColligateSPYearResponse")]
    void UpdateColligateSPYear(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdateColligateSPMonth", ReplyAction="http://tempuri.org/IFuelService/UpdateColligateSPMonthResponse")]
    void UpdateColligateSPMonth(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanGencYear", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanGencYearResponse")]
    void UpdatePlanGencYear(string strId, string strIdea, bool b, byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanGencMonth", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanGencMonthResponse")]
    void UpdatePlanGencMonth(string strId, string strIdea, bool b, byte[] data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanSellYear", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanSellYearResponse")]
    void UpdatePlanSellYear(string strId, string strIdea, bool b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuelService/UpdatePlanRescolligate", ReplyAction="http://tempuri.org/IFuelService/UpdatePlanRescolligateResponse")]
    void UpdatePlanRescolligate(string strId, string strIdea, bool b);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IFuelServiceChannel : IFuelService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class FuelServiceClient : System.ServiceModel.ClientBase<IFuelService>, IFuelService
{
    
    public FuelServiceClient()
    {
    }
    
    public FuelServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FuelServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FuelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FuelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void UpdateFuelChecking(string strId, string strIdea, bool b)
    {
        base.Channel.UpdateFuelChecking(strId, strIdea, b);
    }
    
    public int UpateReport(string id, string upload)
    {
        return base.Channel.UpateReport(id, upload);
    }
    
    public int UpateRmrb(string id, string upload)
    {
        return base.Channel.UpateRmrb(id, upload);
    }
    
    public int SaveBMCompanyMaintain(byte[] data)
    {
        return base.Channel.SaveBMCompanyMaintain(data);
    }
    
    public int SaveBMIndexMaintain(byte[] data)
    {
        return base.Channel.SaveBMIndexMaintain(data);
    }
    
    public int UpdateProblemRectifyBM(string strId, string finishstatus, bool b)
    {
        return base.Channel.UpdateProblemRectifyBM(strId, finishstatus, b);
    }
    
    public WcfService.Service.SafeMeasureTicketTemp[] GetSafeMeasureTicketData()
    {
        return base.Channel.GetSafeMeasureTicketData();
    }
    
    public void UpdateFuelSupplierApply(string strId, string strType)
    {
        base.Channel.UpdateFuelSupplierApply(strId, strType);
    }
    
    public void SaveFuelSupplier(byte[] data)
    {
        base.Channel.SaveFuelSupplier(data);
    }
    
    public int SaveFactoryInfo(byte[] data)
    {
        return base.Channel.SaveFactoryInfo(data);
    }
    
    public int SavePurchaseType(byte[] data)
    {
        return base.Channel.SavePurchaseType(data);
    }
    
    public int SaveFuelKind(byte[] data)
    {
        return base.Channel.SaveFuelKind(data);
    }
    
    public int SaveTransportType(byte[] data)
    {
        return base.Channel.SaveTransportType(data);
    }
    
    public int SavePlanFactoryFee(byte[] data)
    {
        return base.Channel.SavePlanFactoryFee(data);
    }
    
    public int SaveMine(byte[] data)
    {
        return base.Channel.SaveMine(data);
    }
    
    public int SaveStationInfo(byte[] data)
    {
        return base.Channel.SaveStationInfo(data);
    }
    
    public int SavePlanFundVindicate(byte[] data)
    {
        return base.Channel.SavePlanFundVindicate(data);
    }
    
    public int UpdateFuelContract(string strId, string strIdea, bool b)
    {
        return base.Channel.UpdateFuelContract(strId, strIdea, b);
    }
    
    public void UpdatePlanZBMonth(byte[] data)
    {
        base.Channel.UpdatePlanZBMonth(data);
    }
    
    public void UpdatePlanZBYear(byte[] data)
    {
        base.Channel.UpdatePlanZBYear(data);
    }
    
    public void UpdatePlanElecYear(string strId, string strIdea, bool b)
    {
        base.Channel.UpdatePlanElecYear(strId, strIdea, b);
    }
    
    public void UpdatePlanElecMonth(string strId, string strIdea, bool b)
    {
        base.Channel.UpdatePlanElecMonth(strId, strIdea, b);
    }
    
    public void UpdatePlanHotYear(string strId, string strIdea, bool b)
    {
        base.Channel.UpdatePlanHotYear(strId, strIdea, b);
    }
    
    public void UpdatePlanHotMonth(string strId, string strIdea, bool b)
    {
        base.Channel.UpdatePlanHotMonth(strId, strIdea, b);
    }
    
    public void UpdatePlanJJYear(string strId, string strIdea, bool b)
    {
        base.Channel.UpdatePlanJJYear(strId, strIdea, b);
    }
    
    public void UpdatePlanJJMonth(string strId, string strIdea, bool b)
    {
        base.Channel.UpdatePlanJJMonth(strId, strIdea, b);
    }
    
    public void UpdatePlanFuelYear(string strId, string strIdea, bool b)
    {
        base.Channel.UpdatePlanFuelYear(strId, strIdea, b);
    }
    
    public void UpdatePlanFuelMonth(string strId, string strIdea, bool b)
    {
        base.Channel.UpdatePlanFuelMonth(strId, strIdea, b);
    }
    
    public void UpdateNewSetStockYear(string strId, string strIdea, bool b)
    {
        base.Channel.UpdateNewSetStockYear(strId, strIdea, b);
    }
    
    public void UpdateColligateSPYear(string strId, string strIdea, bool b)
    {
        base.Channel.UpdateColligateSPYear(strId, strIdea, b);
    }
    
    public void UpdateColligateSPMonth(string strId, string strIdea, bool b)
    {
        base.Channel.UpdateColligateSPMonth(strId, strIdea, b);
    }
    
    public void UpdatePlanGencYear(string strId, string strIdea, bool b, byte[] data)
    {
        base.Channel.UpdatePlanGencYear(strId, strIdea, b, data);
    }
    
    public void UpdatePlanGencMonth(string strId, string strIdea, bool b, byte[] data)
    {
        base.Channel.UpdatePlanGencMonth(strId, strIdea, b, data);
    }
    
    public void UpdatePlanSellYear(string strId, string strIdea, bool b)
    {
        base.Channel.UpdatePlanSellYear(strId, strIdea, b);
    }
    
    public void UpdatePlanRescolligate(string strId, string strIdea, bool b)
    {
        base.Channel.UpdatePlanRescolligate(strId, strIdea, b);
    }
}
